module.exports = {
	currentEnv: process.env.NODE_ENV,
	database_server: {
		host: process.env.MYSQL_HOST,
		port: process.env.MYSQL_PORT,
		database: process.env.MYSQL_DATABASE,
		user: process.env.MYSQL_USER,
		password: process.env.MYSQL_PASSWORD,
		connectionLimit: 10,
		multipleStatements: true,
	},
	CARTRACK_URL: process.env.CARTRACK_SERVICE_URL,
	CARTRACK_URL_API: process.env.CARTRACK_SERVICE_URL + '/rest',
	CARTRACK_USERNAME: process.env.CARTRACK_SERVICE_USERNAME,
	CARTRACK_API_KEY: process.env.CARTRACK_SERVICE_API_KEY,
	CARTRACK_AUTHORIZATION: "Basic " + btoa(process.env.CARTRACK_SERVICE_USERNAME + ':' + process.env.CARTRACK_SERVICE_API_KEY),
	STRIPE_KEY: process.env.STRIPE_KEY,
	STRIPE_SECRET: process.env.STRIPE_SECRET,
	STRIPE_PAYMENT_RETURN_URL: process.env.APP_PUBLIC_URL + '/payment-result',
	AWS_S3_ACCESS_KEY_SECRET_ID: process.env.AWS_S3_ACCESS_KEY_SECRET_ID,
	AWS_S3_SECRET_KEY_SECRET_ID: process.env.AWS_S3_SECRET_KEY_SECRET_ID,
	AWS_S3_BUCKET: process.env.AWS_S3_BUCKET,
	AWS_S3_REGION: process.env.AWS_S3_REGION,
	USER_SECRET: "visibeen",
	APP_PUBLIC_URL: process.env.APP_PUBLIC_URL,
	MINIMUM_BOOKING_PAYMENT_AMOUNT: 4,
	CHARGE_CURRENT_CODE: 'hkd',
	URL_NOMINATIM_OSM: "https://nominatim.openstreetmap.org/reverse",
	SECURITY_DEPOSIT_BOOKING: 5000,
	LIMIT_FILE_SIZE: 5 * 1024 * 1024,
	MOMENT_LONG_DATE_TIME_FORMAT: 'YYYY-MM-DD HH:mm:ss',
	MOMENT_TIME_FORMAT: "HH:mm:ss",
	MOMENT_DATE_FORMAT: 'YYYY-MM-DD',
	MOMENT_DATE_TIME_FORMAT: 'YYYY-MM-DD HH:mm',
	MOMENT_LONG_DATE_FORMAT: 'dddd DD MMM YYYY',
	TIMEZONE: 'Asia/Calcutta',
	NUMBER_DAYS_EXPIRES_TOKEN: 365
};
